apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigsecret
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiSXZhblRva2FyZXZQIiwicGFzc3dvcmQiOiJnaHBfbEswYzhTUUFXc09JcTQyTlFXYng4M3FLczhHOVJLM2EwWjlSIiwiYXV0aCI6IlNYWmhibFJ2YTJGeVpYWlFPbWRvY0Y5c1N6QmpPRk5SUVZkelQwbHhOREpPVVZkaWVEZ3pjVXR6T0VjNVVrc3pZVEJhT1ZJPSJ9fX0=