@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

class SurveillanceController {
  +getCameras()
  +getRecordings(cameraId)
  +startRecording(cameraId)
  +stopRecording(cameraId)
  +getEvents(cameraId, from, to)
}


interface SurveillanceService {
  +{abstract} getCameras()
  +{abstract} getRecordings(cameraId)
  +{abstract} startRecording(cameraId)
  +{abstract} stopRecording(cameraId)
  +{abstract} getEvents(cameraId, from, to)
}

SurveillanceController --> SurveillanceService : uses

@enduml